Asio/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asio.Models
{
    public class Course
    {
        public int Id { get; set; }

        [StringLength(8)]
        [Display(Name = "Course")]
        public string Code { get; set; }

        [StringLength(50)]
        [Display(Name = "Course name")]
        public string Name { get; set; }

        [Range(1, 30)]
        [Display(Name = "Credits")]
        public int Credits { get; set; }

        [Display(Name = "Teacher")]
        public int TeacherId { get; set; }

        public int SemesterId { get; set; }

        public DateTime _CreatedTime = DateTime.Now;
        public DateTime CreatedTime { get { return _CreatedTime; } set { _CreatedTime = value; } }


        public virtual Teacher Teacher { get; set; }
        public virtual Semester Semester { get; set; }
        public ICollection<Enrollment> Enrollments { get; set; }
    }
}

Asio/Models/CourseViewModel.cs
using System.Collections.Generic;

namespace Asio.Models
{
    public class CourseViewModel
    {
        public Course Course { get; set; }
        public IEnumerable<Enrollment> Enrollments { get; set; }
    }
}

Asio/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asio.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace Asio.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Course
        public ActionResult Index()
        {
            if (User.IsInRole("Teacher")) {
                string currentUserId = User.Identity.GetUserId();
                var courses = db.Courses.Where(c => c.Teacher.User.Id == currentUserId).ToList();
                return View(courses);
            }

            if (User.IsInRole("Student"))
            {
                string currentUserId = User.Identity.GetUserId();

                Student student = db.Students.FirstOrDefault(s => s.UserId == currentUserId);
                if (student != null) { // Check student is existed or not

                    // Select Passed Courses from Enrollment table
                    var enrollments = db.Enrollments.Where(e => e.StudentId == student.Id && e.IsPassed == true).ToList();
                    List<Course> courses = new List<Course>();

                    if (enrollments == null) {
                        return View(courses);
                    }

                    foreach (Enrollment enrollment in enrollments) {
                        Course course = db.Courses.FirstOrDefault(c => c.Id == enrollment.CourseId);
                        if (course != null) {
                            courses.Add(course);
                        }
                    }
                    return View(courses.ToList());

                }

            }

            if (User.IsInRole("Admin"))
            {
                var courses = db.Courses.Include(c => c.Semester);
                return View(courses.ToList());
            }

            return View();
        }

        // GET: Course/Details
        public ActionResult Details(int? id, int? enrollmentId)
        {
            if (id != null)
            {
                Course course = db.Courses.Find(id);
                if (course == null)
                {
                    return HttpNotFound();
                }
            }

            if (enrollmentId != null && (User.IsInRole("Teacher") || User.IsInRole("Admin"))) {
                Enrollment enrollment = db.Enrollments.Find(enrollmentId);
                db.Enrollments.Remove(enrollment);
                db.SaveChanges();
            }         

            var viewModel = new CourseViewModel();
            viewModel.Course = db.Courses.Find(id);
            if (User.IsInRole("Teacher") || User.IsInRole("Admin"))
            {
                viewModel.Enrollments = db.Enrollments.Where(s => s.CourseId == id).ToList();
            }

            return View(viewModel);
        }

        // GET: Course/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Name");
            //ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "UserId");

            var teacher = db.Teachers.Include(c => c.User).Select(c => new SelectListItem {
                Value = c.Id.ToString(),
                Text = c.User.FirstName + " " + c.User.LastName + " ( " + c.User.UserName + " ) "
            });
            try
            {
                ViewBag.TeacherId = new SelectList(teacher, "Value", "Text");
            }
            catch (Exception e) {
                System.Diagnostics.Debug.WriteLine(e.Message);
            }

            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Code,Name,Credits,TeacherId,SemesterId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Name", course.SemesterId);
            //ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "UserId", course.TeacherId);
            ViewBag.TeacherId = new SelectList(db.Teachers.Include(c => c.User), "Value", "Text", course.TeacherId);
            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // GET: Course/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Name", course.SemesterId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "UserId", course.TeacherId);
            return View(course);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Code,Name,Credits,TeacherId,SemesterId,CreatedTime")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Name", course.SemesterId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "UserId", course.TeacherId);
            return View(course);
        }

        // GET: Course/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Course/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Asio/Controllers/EnrollmentController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Asio.Models;
using IdentitySample.Models;
using System.Web.UI;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;

namespace Asio.Controllers
{
    [Authorize]
    public class EnrollmentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Enrollment
        [Authorize(Roles = "Student")]
        public ActionResult Index()
        {
            string currentUserId = User.Identity.GetUserId();

            Student student = db.Students.FirstOrDefault(s => s.UserId == currentUserId);
            if (student == null) // Check student is existed or not
            {
                return HttpNotFound();
            }

            // Select Passed Courses from Enrollment table
            var enrollments = db.Enrollments.Where(e => e.StudentId == student.Id).ToList();
            return View(enrollments);
        }

        // GET: Enrollment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollment/Create
        public ActionResult Create()
        {
            var viewModel = new EnrollmentViewModel();

            // Teacher can enroll to his course only
            if (User.IsInRole("Teacher"))
            {
                string currentUserId = User.Identity.GetUserId();
                var courses = db.Courses.Where(c => c.Teacher.User.Id == currentUserId).ToList();
                viewModel.Courses = courses;
            }

            // Student can enroll to courses he has not joined
            if (User.IsInRole("Student"))
            {
                string currentUserId = User.Identity.GetUserId();

                Student student = db.Students.FirstOrDefault(s => s.UserId == currentUserId);
                if (student == null) // Check student is existed or not
                {
                    return HttpNotFound();
                }
                // Select Passed course from Enrollment table
                var enrollments = db.Enrollments.Where(e => e.StudentId == student.Id).ToList();
                var courses = db.Courses.ToList();

                if (enrollments == null)
                {
                    return View(courses);
                }

                foreach (Enrollment enrollment in enrollments)
                {
                    Course course = db.Courses.FirstOrDefault(c => c.Id == enrollment.CourseId);
                    if (course == null)
                    {
                        return HttpNotFound();
                    }
                    courses.Remove(course);
                }
                viewModel.Courses = courses;
                viewModel.UserName = User.Identity.GetUserName();
           }

            if (User.IsInRole("Admin"))
            {
                var courses = db.Courses.Include(c => c.Semester).ToList();
                viewModel.Courses = courses;
            }
            //viewModel.Courses = db.Courses.ToList();
            ViewData["Error"] = null;
            ViewData["Success"] = null;
            return View(viewModel);
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,SelectedCourses")] EnrollmentViewModel enrollModel)
        {
            if (ModelState.IsValid)
            {
                System.Diagnostics.Debug.WriteLine(enrollModel.UserName);

                ApplicationUser user = db.Users.FirstOrDefault(u => u.UserName == enrollModel.UserName);
                if (user != null) //check user is existed or not
                {
                    Student student = db.Students.FirstOrDefault(s => s.UserId == user.Id);
                    if (student != null) //check student is existed or not
                    {
                        EnrollmentViewModel enrollment = new EnrollmentViewModel();
                        enrollment.SelectedCourses = enrollModel.SelectedCourses;
                        foreach (var item in enrollModel.SelectedCourses)
                        {
                            //check Enrollment is exited or not
                            Enrollment enroll = db.Enrollments.FirstOrDefault(e => e.StudentId == student.Id && e.CourseId == item);
                            if (enroll == null)
                            {
                                enroll = new Enrollment { StudentId = student.Id, CourseId = item };
                                db.Enrollments.Add(enroll);
                                db.SaveChanges();
                            }
                            else {
                                ViewData["Error"] += db.Courses.Find(item).Name + ", ";
                                enrollModel.Courses = db.Courses.ToList();
                                return View(enrollModel);
                            }
                        }
                    }
                    else {
                        ViewData["Error"] = "Student is not existed! Please input other!";
                        enrollModel.Courses = db.Courses.ToList();
                        return View(enrollModel);
                    }
                }
                else {
                    ViewData["Error"] = "User is not existed! Please input other!";
                    enrollModel.Courses = db.Courses.ToList();
                    return View(enrollModel);
                }               

            }

            //Enroll successfully!
            TempData["Success"] = "Enrollment successfully!";
            return RedirectToAction("Create");
        }

        // GET: Enrollment/Edit/5
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.Course = enrollment.Course;
            ViewBag.Student = enrollment.Student;
            ViewData["Success"] = null;
            return View(enrollment);
        }

        // POST: Enrollment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StudentId,CourseId,Grade,IsPassed")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
            }

            enrollment = db.Enrollments.FirstOrDefault(e => e.StudentId == enrollment.StudentId);
            ViewBag.Course = enrollment.Course;
            ViewBag.Student = enrollment.Student;
            TempData["Success"] = "Enrollment successfully!";
            return View(enrollment);
        }

        [Authorize(Roles = "Admin")]
        // GET: Enrollment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);

            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        [Authorize(Roles = "Admin")]
        // POST: Enrollment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Asio/Views/Course/Create.cshtml
@model Asio.Models.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" }, placeholder = "eg. KY103D" })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" }, placeholder = "eg. ASP.net" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" }, placeholder = "eg. 5" })
                @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "TeacherId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemesterId, "SemesterId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SemesterId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SemesterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Asio/Views/Course/Delete.cshtml
@model Asio.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Semester.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Semester.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Asio/Views/Course/Details.cshtml
@model Asio.Models.CourseViewModel

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Course.Name);
}

<h2>@Html.DisplayFor(model => model.Course.Name)</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Credits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Credits)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Semester.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Semester.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.TeacherId)
        </dt>

        <dd>
            @Html.DisplayFor(model=> model.Course.Teacher.User.FirstName) @Html.DisplayFor(model => model.Course.Teacher.User.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.CreatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CreatedTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Course.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@if ((User.IsInRole("Teacher") || User.IsInRole("Admin")) && Model.Enrollments.Count() > 0)
{
    <h3>
        Students Enrolled in Selected Course
    </h3>
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            @*<th>
                Group
            </th>*@
            <th>
                Grade
            </th>
            <th>
                Last changed
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.User.FullName) (@Html.DisplayFor(modelItem => item.Student.User.UserName))
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Student.Group.Name)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedTime)
                </td>

                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Disenroll", "Details", new { id = Model.Course.Id, enrollmentId = item.Id })
                    </td>
                }

                @if (User.IsInRole("Teacher"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Enrollment", new { id = item.Id }, null) |
                        @Html.ActionLink("Disenroll", "Details", new { id = Model.Course.Id, enrollmentId = item.Id })
                    </td>
                }

            </tr>
        }
    </table>
}

Asio/Views/Course/Edit.cshtml
@model Asio.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "TeacherId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemesterId, "SemesterId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SemesterId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SemesterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Asio/Views/Course/Index.cshtml
@model IEnumerable<Asio.Models.Course>

@{
    ViewBag.Title = "Courses";
}

@if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
{
    <h2>All Courses</h2>

}

@if (User.IsInRole("Student"))
{
    <h2>All Passed Courses</h2>

}

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Credits)
                </td>

                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                }

                @if (User.IsInRole("Teacher") || User.IsInRole("Student"))
                {
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </td>
                }
            </tr>

        }
    </table>
}
else {
    <h4>No Passed Course to show!</h4>
}